import { extraCategories, extraReferences, extraQuestions } from './archiveQuestionsExpansion.js'

// 按 2024–2026 面试准备中的常见考查方向整理；不代表特定企业原题或频率统计。
export const archiveCategories = [
  { id: 'javascript', name: 'JavaScript 基础', short: 'JavaScript', en: 'LANGUAGE & RUNTIME', description: '从执行机制到异步与对象模型，把“为什么”讲清楚。' },
  { id: 'css', name: 'CSS 与布局', short: 'CSS', en: 'LAYOUT & STYLING', description: '层叠、布局和响应式，是界面问题的常见起点。' },
  { id: 'react', name: 'React 原理', short: 'React', en: 'COMPONENT & STATE', description: '围绕状态身份、副作用与渲染性能展开。' },
  { id: 'performance', name: '系统与性能优化', short: '性能优化', en: 'MEASURE & IMPROVE', description: '从指标与瓶颈定位出发，解释实际优化路径。' },
  { id: 'webpack', name: 'Webpack 工程化', short: 'Webpack', en: 'BUNDLE & BUILD', description: '理解模块图、构建扩展点和产物优化。' },
  { id: 'vite', name: 'Vite 工程化', short: 'Vite', en: 'DEV & PRODUCTION', description: '结合本项目的 Vite 6，区分开发体验与生产构建。' },
  ...extraCategories,
]

export const archiveReferences = {
  eventLoop: { label: 'MDN · 事件循环', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop' },
  microtasks: { label: 'MDN · 微任务', url: 'https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide' },
  closures: { label: 'MDN · 闭包', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures' },
  this: { label: 'MDN · this', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this' },
  inheritance: { label: 'MDN · 继承与原型链', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain' },
  promises: { label: 'MDN · Promise 组合', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises' },
  structuredClone: { label: 'MDN · structuredClone', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone' },
  cascade: { label: 'MDN · 层叠优先级', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascade/Specificity' },
  layers: { label: 'MDN · 层叠层', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Cascade_layers' },
  flex: { label: 'MDN · Flex 布局', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Flexible_box_layout/Basic_concepts' },
  bfc: { label: 'MDN · BFC', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Display/Block_formatting_context' },
  grid: { label: 'MDN · Grid 布局', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Grid_layout' },
  stacking: { label: 'MDN · 层叠上下文', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Positioned_layout/Stacking_context' },
  containerQueries: { label: 'MDN · 容器查询', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Containment/Container_queries' },
  reactState: { label: 'React · 状态快照', url: 'https://react.dev/learn/state-as-a-snapshot' },
  reactBatching: { label: 'React · 批量更新', url: 'https://react.dev/learn/queueing-a-series-of-state-updates' },
  reactKeys: { label: 'React · 状态保留与重置', url: 'https://react.dev/learn/preserving-and-resetting-state' },
  reactEffect: { label: 'React · Effect', url: 'https://react.dev/learn/synchronizing-with-effects' },
  reactMemo: { label: 'React · useMemo', url: 'https://react.dev/reference/react/useMemo' },
  reactTransition: { label: 'React · useTransition', url: 'https://react.dev/reference/react/useTransition' },
  reactHydration: { label: 'React · hydrateRoot', url: 'https://react.dev/reference/react-dom/client/hydrateRoot' },
  vitals: { label: 'web.dev · Core Web Vitals', url: 'https://web.dev/articles/vitals' },
  inp: { label: 'web.dev · INP', url: 'https://web.dev/articles/inp' },
  lcp: { label: 'web.dev · LCP', url: 'https://web.dev/articles/lcp' },
  cls: { label: 'web.dev · CLS', url: 'https://web.dev/articles/cls' },
  lazyLoading: { label: 'MDN · 懒加载', url: 'https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Lazy_loading' },
  cache: { label: 'MDN · HTTP 缓存', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching' },
  abortController: { label: 'MDN · AbortController', url: 'https://developer.mozilla.org/en-US/docs/Web/API/AbortController' },
  longTasks: { label: 'web.dev · 长任务', url: 'https://web.dev/articles/long-tasks-devtools' },
  virtualization: { label: 'TanStack · 虚拟列表', url: 'https://tanstack.com/virtual/latest/docs/introduction' },
  webpackConcepts: { label: 'Webpack · 核心概念', url: 'https://webpack.js.org/concepts/' },
  webpackLoaders: { label: 'Webpack · Loaders', url: 'https://webpack.js.org/concepts/loaders/' },
  webpackPlugins: { label: 'Webpack · Plugins', url: 'https://webpack.js.org/concepts/plugins/' },
  webpackSplitting: { label: 'Webpack · Code splitting', url: 'https://webpack.js.org/guides/code-splitting/' },
  webpackTree: { label: 'Webpack · Tree shaking', url: 'https://webpack.js.org/guides/tree-shaking/' },
  webpackCache: { label: 'Webpack · Cache', url: 'https://webpack.js.org/configuration/cache/' },
  webpackHmr: { label: 'Webpack · HMR', url: 'https://webpack.js.org/concepts/hot-module-replacement/' },
  viteWhy: { label: 'Vite 6 · 为什么选择 Vite', url: 'https://v6.vite.dev/guide/why' },
  viteDeps: { label: 'Vite 6 · 依赖预打包', url: 'https://v6.vite.dev/guide/dep-pre-bundling' },
  viteFeatures: { label: 'Vite 6 · 功能与 HMR', url: 'https://v6.vite.dev/guide/features' },
  viteEnv: { label: 'Vite 6 · 环境变量', url: 'https://v6.vite.dev/guide/env-and-mode' },
  viteBuild: { label: 'Vite 6 · 生产构建', url: 'https://v6.vite.dev/guide/build' },
  vitePlugins: { label: 'Vite 6 · 插件 API', url: 'https://v6.vite.dev/guide/api-plugin' },
  ...extraReferences,
}

const baseArchiveQuestions = [
  {
    id: 'js-event-loop', category: 'javascript', level: '基础', title: 'Promise.then、queueMicrotask 与 setTimeout 的执行顺序如何判断？',
    brief: '先跑同步代码，再清空微任务队列，最后处理下一轮任务。',
    answer: [
      '先执行当前调用栈上的同步代码。Promise 回调和 queueMicrotask 会进入微任务队列；setTimeout 的回调作为后续任务，在达到最短延时后才有机会执行。当前任务结束时，浏览器会先运行微任务检查点，再选择下一个任务。',
      '判断输出题时应按“同步栈 → 当前任务产生的微任务 → 下一任务”逐步列队。Promise.then 与 queueMicrotask 都排入微任务队列，通常按入队先后执行。微任务执行时若继续加入微任务，会在本次检查点继续处理，因此过量微任务可能推迟渲染和用户交互。',
      '不要把 setTimeout(fn, 0) 理解为“立即执行”；它仍要等待当前任务、微任务和事件循环调度。',
    ],
    example: 'console.log(1);\nsetTimeout(() => console.log(4), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(2);\n// 1 2 3 4',
    followUp: '如果 Promise 回调里再创建一个 Promise 回调，它与已排队的微任务谁先执行？',
    refs: ['eventLoop', 'microtasks'],
  },
  {
    id: 'js-closure', category: 'javascript', level: '基础', title: '什么是闭包？它为什么能保留变量，也可能造成内存问题？',
    brief: '函数携带其创建时的词法环境，关键是引用仍可达。',
    answer: [
      '闭包指函数及其创建时可访问的词法环境。内部函数即使在外部函数返回后执行，仍可读取它捕获的变量；这让私有状态、函数工厂和事件回调成为可能。',
      '是否保留内存取决于引用是否仍可达。长期存活的监听器、计时器或缓存闭包若持有大型对象，会使这些对象不能被回收。解绑监听器、清理计时器并缩小捕获范围，通常比“避免闭包”更有效。',
      '面试中可用计数器说明：每次调用工厂函数会产生独立的词法环境，多个返回函数共享同一次调用中的状态。',
    ],
    example: 'function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\nconst next = makeCounter();\nnext(); // 1\nnext(); // 2',
    followUp: '循环中创建回调时，var 与 let 为什么可能得到不同结果？',
    refs: ['closures'],
  },
  {
    id: 'js-this', category: 'javascript', level: '基础', title: '普通函数与箭头函数的 this 如何确定？call、apply、bind 有什么区别？',
    brief: '普通函数看调用方式；箭头函数从外层词法作用域取得 this。',
    answer: [
      '普通函数的 this 通常由调用方式决定：obj.fn() 指向 obj；通过 call/apply 显式指定时使用传入值；new 调用会绑定到新对象。严格模式下直接调用普通函数，this 为 undefined。',
      '箭头函数不创建自己的 this，会读取定义位置外层的 this，所以 call/apply/bind 不能改变它的 this。它适合在回调中保留外层上下文，但不适合当作需要动态 this 的对象方法或构造函数。',
      'call 逐个传参数并立即调用；apply 用数组形式传参数并立即调用；bind 返回一个绑定后的新函数，等待稍后调用。',
    ],
    example: 'const box = { value: 7, read() { return this.value; } };\nconst read = box.read;\nread.call(box); // 7\nconst later = read.bind(box);\nlater(); // 7',
    followUp: '把对象方法取出作为回调传递，为什么会“丢失 this”？',
    refs: ['this'],
  },
  {
    id: 'js-prototype', category: 'javascript', level: '进阶', title: 'new 做了什么？class 与原型链是什么关系？',
    brief: '属性查找沿原型链进行，class 是更清晰的语法形式。',
    answer: [
      '用 new 调用构造函数时，会创建新对象，使其原型指向构造函数的 prototype，再以新对象作为 this 执行构造逻辑。若构造函数显式返回对象，该对象可能成为最终结果；否则返回新对象。',
      '读取对象属性时，如果自身没有，就沿内部原型链向上查找，直到找到或到达 null。实例共享的方法通常放在原型上，而每个实例独有的数据放在实例自身。',
      'class 提供构造器、方法和继承的语法，但实例方法仍位于原型上。面试时要区分“构造函数的 prototype”与“实例的内部原型”。',
    ],
    example: 'class User {\n  constructor(name) { this.name = name; }\n  greet() { return this.name; }\n}\nconst user = new User("Lin");\nObject.getPrototypeOf(user) === User.prototype; // true',
    followUp: 'Object.create(proto) 与 new 构造对象，结果中的原型链有什么共同点？',
    refs: ['inheritance'],
  },
  {
    id: 'js-promise', category: 'javascript', level: '进阶', title: 'Promise.all、allSettled、race、any 分别适合什么场景？',
    brief: '区分“全部成功”“全部结束”“最先落定”和“最先成功”。',
    answer: [
      'Promise.all 要所有输入都成功才兑现；任一拒绝就立即拒绝，适合彼此独立但结果都必需的请求。allSettled 等所有输入都落定，并给出每项的成功或失败状态，适合批量任务汇总。',
      'race 采用最先落定的结果，无论成功失败；any 采用最先成功的结果，若全部失败会以 AggregateError 拒绝。它们描述的是结果聚合规则，不会自动取消其他仍在运行的操作。',
      '并发量受限时不要直接对海量请求使用 Promise.all，应使用队列或并发池。需要取消 fetch 时，要另配 AbortController。',
    ],
    example: 'const results = await Promise.allSettled([\n  fetch("/api/a"), fetch("/api/b")\n]);\nconst failures = results.filter(x => x.status === "rejected");',
    followUp: 'race 用来实现超时后，为什么还需要取消未完成的请求？',
    refs: ['promises'],
  },
  {
    id: 'js-copy', category: 'javascript', level: '实战', title: '浅拷贝与深拷贝怎么区分？structuredClone 能替代 JSON 方案吗？',
    brief: '先说明对象引用的共享，再说明不同复制方法的边界。',
    answer: [
      '展开运算符和 Object.assign 只复制第一层属性；嵌套对象的引用仍然共享。若随后修改嵌套对象，两份数据可能一起变化。',
      'JSON.stringify/parse 会丢失或改变一些值，例如 undefined、函数、循环引用、Date、Map 等，不是通用深拷贝。structuredClone 能复制许多内建可克隆类型，也能处理循环引用和可转移对象，但函数与 DOM 节点等不可克隆。',
      '工程实践应先问“是否真的需要完整深拷贝”。React 状态更新通常只复制发生变化的路径；大对象全量复制会增加时间与内存成本。',
    ],
    example: 'const a = { profile: { name: "Lin" } };\nconst b = { ...a };\nb.profile.name = "Ming";\nconsole.log(a.profile.name); // "Ming"',
    followUp: '更新嵌套 React state 时，怎样只复制变动路径？',
    refs: ['structuredClone'],
  },

  {
    id: 'css-cascade', category: 'css', level: '基础', title: 'CSS 样式冲突时，层叠、优先级和 !important 如何一起判断？',
    brief: '先看来源与重要性、层叠层，再在同一层里比选择器权重。',
    answer: [
      '不要直接数 ID 和 class。浏览器先比较来源、重要性和层叠层；只有仍处于同一竞争层级的声明，才比较选择器优先级。最后还可能由作用域距离和源码顺序决定。',
      '选择器权重可按 ID、class/属性/伪类、元素/伪元素三列比较。:where() 的权重为零。!important 改变层叠中的重要性顺序，并非给选择器“加一万分”。',
      '大型项目中，可用 @layer 规定基础样式、组件样式和覆盖样式的次序，少依赖越来越长的选择器。',
    ],
    example: '@layer base, components;\n@layer base { .button { color: gray; } }\n@layer components { .button { color: green; } }\n/* 同为普通作者样式时，后声明的层优先 */',
    followUp: '为什么未放入层的普通作者样式可能覆盖层内的高权重选择器？',
    refs: ['cascade', 'layers'],
  },
  {
    id: 'css-flex', category: 'css', level: '实战', title: 'Flex 子项明明设置了 flex: 1，为什么内容还是把布局撑破？',
    brief: '默认最小尺寸可能由内容决定，先检查 min-width: 0。',
    answer: [
      'flex: 1 允许项目分配剩余空间，但项目在主轴上的自动最小尺寸可能受内容的 min-content 宽度约束。长单词、代码或不换行文字会使项目不能缩到期望宽度。',
      '常见修复是给需要收缩的子项设 min-width: 0；纵向 Flex 则检查 min-height: 0。之后再决定 overflow、换行或省略号的表现。',
      '面试时最好说明原因而不是只背一行 CSS：flex-shrink 不是无条件把内容压小，最小尺寸仍参与约束。',
    ],
    example: '.layout { display: flex; }\n.main { flex: 1; min-width: 0; }\n.title { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
    followUp: '纵向 Flex 布局中的可滚动内容区域，为什么可能还需要 min-height: 0？',
    refs: ['flex'],
  },
  {
    id: 'css-bfc', category: 'css', level: '基础', title: '什么是 BFC？什么时候用 flow-root 比 overflow: hidden 更合适？',
    brief: 'BFC 是独立的块级格式化上下文，可用于隔离布局行为。',
    answer: [
      '块级格式化上下文决定其内部块盒的布局。创建新的 BFC 可以容纳内部浮动，也可避免自身内容与外部浮动重叠，并阻止某些外边距折叠关系。',
      'display: flow-root 会显式创建 BFC，表达“我要隔离布局”这一意图。overflow: hidden 也可能创建 BFC，但同时会裁剪溢出内容，可能把阴影、浮层或焦点轮廓切掉。',
      '不要把 BFC 当万能布局方案；现代页面的主布局通常优先用 Flex 或 Grid，BFC 更适合解释浮动与块级流中的特定现象。',
    ],
    example: '.article { display: flow-root; }\n.article img { float: left; margin-right: 16px; }',
    followUp: '父元素只包含浮动子元素时，为什么高度看起来会塌陷？',
    refs: ['bfc'],
  },
  {
    id: 'css-grid-flex', category: 'css', level: '基础', title: 'Flex 与 Grid 如何选？一维、二维是什么意思？',
    brief: 'Flex 主要沿一个主轴分配空间；Grid 同时描述行与列。',
    answer: [
      '导航、按钮组、单行对齐通常适合 Flex；卡片墙、仪表盘、明确的行列区域通常适合 Grid。Flex 也能换行，但每一行的空间分配相对独立；Grid 的列轨道可在多行间对齐。',
      'Grid 的 repeat、minmax 和 auto-fit 能用少量规则创建自适应列数。两者可嵌套：外层 Grid 管页面区域，卡片内部 Flex 管文字与按钮对齐。',
      '选择时先画出布局约束，而非只根据元素数量决定。若要跨行对齐列宽，Grid 往往更自然。',
    ],
    example: '.cards {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(100%, 240px), 1fr));\n  gap: 16px;\n}',
    followUp: 'auto-fit 与固定列数相比，页面缩窄时会怎样变化？',
    refs: ['grid', 'flex'],
  },
  {
    id: 'css-stacking', category: 'css', level: '进阶', title: 'z-index 写到 9999，弹层为什么仍然被别的元素盖住？',
    brief: '先检查祖先是否形成了独立的层叠上下文。',
    answer: [
      'z-index 只在相关的层叠上下文内比较。transform、opacity 小于 1、某些定位与 z-index 组合等都可能创建新的层叠上下文；子元素无法靠一个很大的 z-index 跳出祖先上下文。',
      '定位问题时应沿祖先链检查层叠上下文、裁剪和 overflow。弹窗类 UI 常用 Portal 放到靠近文档根部的位置，再统一管理层级。',
      '不要把“z-index 越大越靠前”当全局规则；两个不同上下文之间，先比较它们所属上下文在父级中的层级。',
    ],
    example: '.parent { position: relative; transform: translateZ(0); z-index: 1; }\n.dialog { position: absolute; z-index: 9999; }\n/* dialog 仍被限制在 parent 的层叠上下文里 */',
    followUp: 'Portal 可以解决层叠问题，但还需要考虑哪些定位与焦点管理问题？',
    refs: ['stacking'],
  },
  {
    id: 'css-container', category: 'css', level: '进阶', title: '媒体查询与容器查询的差异是什么？组件库更适合哪一种？',
    brief: '前者看视口，后者看容器；可复用组件常需要后者。',
    answer: [
      '@media 根据视口或设备特征切换样式，适合整体页面断点。容器查询让组件根据某个祖先容器的尺寸调整自身，不必假设它一定处于某个屏幕宽度。',
      '先用 container-type 声明查询容器，再在 @container 中写条件。卡片可能同时出现在侧栏与主内容区，视口宽度相同但可用空间不同，此时容器查询更贴近组件实际约束。',
      '两者可以配合：页面结构用媒体查询，嵌入式或可复用组件用容器查询。仍需设计最小宽度、溢出和内容重排。',
    ],
    example: '.card-wrap { container-type: inline-size; }\n@container (min-width: 440px) {\n  .card { display: grid; grid-template-columns: 120px 1fr; }\n}',
    followUp: '如果没有合适的查询容器，@container 条件会作用到谁？',
    refs: ['containerQueries'],
  },

  {
    id: 'react-state', category: 'react', level: '基础', title: '连续调用两次 setCount(count + 1)，为什么通常只加 1？',
    brief: '同一次渲染里的 count 是固定快照，函数式更新可串联前值。',
    answer: [
      '事件处理函数读取的是创建它那次渲染的 state 快照。两次 setCount(count + 1) 都可能提交同一个新值；React 会批量处理更新，避免每次 setter 立即触发独立渲染。',
      '当下一个值依赖上一个值时，使用 setCount(c => c + 1)。React 会按更新队列顺序调用这些更新函数，因此连续两次可加 2。',
      'setter 之后立即打印当前作用域中的 count，通常还是旧快照。想观察已提交的状态，可直接在下一次渲染中显示，或按同步外部系统的需要使用 Effect。',
    ],
    example: 'setCount(c => c + 1);\nsetCount(c => c + 1); // 在同一事件中累计加 2',
    followUp: '为什么不建议为了拿到“最新 state”而把普通计算都放进 useEffect？',
    refs: ['reactState', 'reactBatching'],
  },
  {
    id: 'react-keys', category: 'react', level: '基础', title: 'React 的 key 只是消除警告吗？它会怎样影响组件状态？',
    brief: 'key 参与组件身份判断，影响保留、移动和重置状态。',
    answer: [
      'React 会根据元素在树中的位置、类型和 key 关联前后两次渲染。列表重排时，稳定 key 让某一项继续对应原来的组件状态；使用下标作为 key，在插入或排序时可能造成输入值、焦点等状态错位。',
      'key 也可以主动重置状态：给同一位置的表单一个不同 key，React 会把它视为新实例并重新初始化。',
      'key 只需在同级兄弟之间唯一，通常使用数据中的稳定 ID。不要在每次渲染时生成随机 key，否则会持续卸载并重建。',
    ],
    example: '{users.map(user => <UserRow key={user.id} user={user} />)}\n<EditForm key={selectedUserId} userId={selectedUserId} />',
    followUp: '什么时候用数组下标作为 key 仍然可以接受？',
    refs: ['reactKeys'],
  },
  {
    id: 'react-effect', category: 'react', level: '实战', title: 'useEffect 的清理函数何时执行？为什么开发环境可能出现“执行两次”？',
    brief: 'Effect 用来同步外部系统；清理要与建立过程对称。',
    answer: [
      'Effect 在提交后运行。依赖变化时，React 先用旧值执行上一次 Effect 的清理，再运行新的 Effect；组件卸载时也会清理。监听器、订阅、计时器和连接都应在对应清理函数中释放。',
      '开发环境启用 StrictMode 时，React 会额外执行一次建立与清理的检查，帮助发现清理不完整的问题。这不是生产环境每次都会额外执行一次业务操作的保证。',
      '不要把 Effect 当成所有逻辑的默认容器。纯粹由 props/state 派生的数据可在渲染时计算；由用户点击直接触发的动作通常放事件处理函数中。',
    ],
    example: 'useEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id);\n}, [tick]);',
    followUp: '请求结果晚于组件卸载或查询条件变化时，怎样避免旧结果覆盖新结果？',
    refs: ['reactEffect'],
  },
  {
    id: 'react-memo', category: 'react', level: '进阶', title: 'React.memo、useMemo、useCallback 分别缓存什么？为什么不能到处加？',
    brief: '分别针对组件渲染、计算结果和函数引用，先测量再使用。',
    answer: [
      'React.memo 可以在 props 未变化时跳过组件重新渲染；useMemo 缓存计算结果；useCallback 缓存函数引用。它们都不是业务正确性的前提，依赖或比较方式写错还可能带来旧值问题。',
      '当子组件开销大、父组件频繁更新且传入 props 可保持稳定时，memo 才更可能有收益。若每次都创建新对象或新函数，浅比较可能无法跳过。',
      '优化前先用 React DevTools Profiler 找到真正耗时的组件，再比较加缓存前后的提交时间。缓存本身也有维护与比较成本。',
    ],
    example: 'const visible = useMemo(() => filter(items, query), [items, query]);\nconst onSelect = useCallback(id => setSelected(id), []);',
    followUp: '子组件已经包了 React.memo，为什么父组件更新后它仍会渲染？',
    refs: ['reactMemo'],
  },
  {
    id: 'react-transition', category: 'react', level: '进阶', title: '输入框筛选大列表卡顿，useTransition 能解决什么，不能解决什么？',
    brief: '把非紧急更新标记为可中断，不能代替减少实际工作量。',
    answer: [
      '输入值更新需要及时响应，列表计算和渲染可以作为较低优先级的过渡更新。useTransition 提供 pending 状态，并让过渡更新在更紧急的更新到来时被打断，改善交互响应。',
      '它不会使昂贵计算凭空消失，也不会缩小列表 DOM。若真正瓶颈是 10,000 行渲染，还需要虚拟化、拆分计算、缓存或改变数据量。',
      '受控输入的值本身不要放到 Transition 中，否则打字反馈可能不及时。面试时要明确区分“调度优先级”与“减少总工作量”。',
    ],
    example: 'setInput(next);\nstartTransition(() => setFilter(next));\n// 输入立即更新，结果列表可稍后更新',
    followUp: 'useDeferredValue 与 useTransition 分别适合由谁控制的更新？',
    refs: ['reactTransition'],
  },
  {
    id: 'react-hydration', category: 'react', level: '进阶', title: 'SSR 页面出现 hydration mismatch，常见原因和排查路径是什么？',
    brief: '服务端首屏 HTML 与客户端首次渲染结果必须一致。',
    answer: [
      'Hydration 会把客户端 React 接到服务端已有的 HTML 上。若两端首次渲染的文本或结构不一致，例如直接读取 window、使用随机数或当前时间、依赖不同的本地状态，就可能出现不匹配。',
      '排查时先比较服务端输出和客户端首次渲染，定位具体节点；将浏览器专属数据放到 Effect 后读取，或在服务端把同一份初始数据序列化传给客户端。',
      '不应把 suppressHydrationWarning 当通用修复。它只能用于确有不可避免差异的局部位置，且不会自动修正所有结构问题。',
    ],
    example: '// 首次渲染先使用相同默认值；挂载后再读取浏览器数据。\nconst [theme, setTheme] = useState("light");\nuseEffect(() => setTheme(localStorage.getItem("theme") || "light"), []);',
    followUp: '为什么 Date.now() 直接出现在 SSR 组件的 JSX 中有风险？',
    refs: ['reactHydration'],
  },

  {
    id: 'perf-vitals', category: 'performance', level: '基础', title: 'LCP、INP、CLS 分别衡量什么？从哪里开始排查？',
    brief: '分别看主要内容显示、交互响应和视觉稳定性。',
    answer: [
      'LCP 关注视口内最大内容元素的呈现时间；INP 关注页面交互到下一次绘制的响应表现；CLS 衡量意外布局位移。常用“良好”阈值分别是 LCP 不超过 2.5 秒、INP 不超过 200 毫秒、CLS 不超过 0.1，并通常看真实用户数据的第 75 百分位。',
      '先确认指标来自真实用户还是实验室测试，并按设备、网络和页面类型分组。LCP 查资源发现与下载、服务端响应和渲染阻塞；INP 查主线程任务；CLS 查图片尺寸、字体和动态插入内容。',
      '不要只盯一个总分。指标反映不同体验，优化方案应对应具体瓶颈，并用改动前后的同口径数据验证。',
    ],
    followUp: '为什么一次本地 Lighthouse 分数与真实用户的第 75 百分位可能差很多？',
    refs: ['vitals', 'inp', 'lcp', 'cls'],
  },
  {
    id: 'perf-inp', category: 'performance', level: '实战', title: '点击按钮反应慢，如何区分事件处理、布局和绘制的耗时？',
    brief: '用 Performance 时间线找长任务与交互后的下一次绘制。',
    answer: [
      '录制浏览器 Performance，观察交互相关的任务：输入延迟、事件回调执行、样式与布局、绘制各占多少。若主线程正被长任务占住，事件可能迟迟不能开始；若回调里做大量同步计算，处理阶段会变长。',
      '把非紧急工作拆成小任务、减少同步 JavaScript、避免反复读写布局属性导致强制同步布局；对大列表减少实际挂载节点。拆任务还要保证用户操作真正依赖的更新先完成。',
      '优化后用相同设备与操作复测，同时看真实用户 INP 分布。单纯把工作塞进 setTimeout 并不保证体验变好。',
    ],
    followUp: '为什么处理函数很短，INP 仍可能很高？',
    refs: ['inp', 'longTasks'],
  },
  {
    id: 'perf-lcp-image', category: 'performance', level: '实战', title: '首屏大图是 LCP 元素时，应如何优化加载链路？',
    brief: '尽早发现关键图片，并减少传输与解码成本。',
    answer: [
      '先在性能工具里确认真正的 LCP 元素及其资源请求时间。首屏关键图若藏在晚执行的 JavaScript 或 CSS 背景中，浏览器发现得晚；可以让它直接出现在 HTML 中，必要时预加载并设置合理的 fetchpriority。',
      '提供匹配显示尺寸的图片、现代格式和响应式 srcset，避免下载远大于实际展示面积的资源。首屏 LCP 图通常不应 lazy-load；屏幕下方图片则适合懒加载。',
      '如果资源下载快但 LCP 仍晚，应继续检查服务端响应、阻塞 CSS、主线程执行和最终渲染延迟，而不是只压缩图片。',
    ],
    followUp: '为什么给所有图片都加 preload 反而可能拖慢页面？',
    refs: ['lcp', 'lazyLoading'],
  },
  {
    id: 'perf-cls', category: 'performance', level: '实战', title: '页面加载时卡片突然下移，如何定位并修复 CLS？',
    brief: '为异步出现的内容预留空间，并检查字体与广告位。',
    answer: [
      'CLS 记录非预期的布局位移。常见原因是没有宽高的图片、异步广告或推荐模块插入到已有内容上方，以及字体替换导致文本尺寸变化。',
      '先用 Performance 的 Layout Shift 记录定位被移动的元素和实际触发源。给图片设置 width/height 或 aspect-ratio，为异步区块预留合理最小高度，并审视字体加载策略。',
      '不能只在视觉上“把元素挪回去”；要让浏览器在首轮布局时就知道空间。用户主动交互后紧接发生的位移有不同计分规则，但仍应关注体验。',
    ],
    followUp: '为什么造成位移的元素不一定就是工具里高亮的那个元素？',
    refs: ['cls'],
  },
  {
    id: 'perf-cache', category: 'performance', level: '进阶', title: '静态资源如何做长期缓存？为什么 HTML 与带 hash 的 JS 策略不同？',
    brief: 'HTML 保持可更新，内容寻址资源可长期缓存。',
    answer: [
      '打包产物的文件名包含内容 hash 时，内容变化会得到新 URL；旧文件可配较长缓存期和 immutable。HTML 通常不使用同样的长期强缓存，因为它负责引用最新资源，需要可重新验证或较短缓存。',
      '缓存命中不等于页面一定使用最新代码。部署时要保证 HTML 引用的新资源已经上传，旧资源不要过早删除，避免仍打开旧页面的用户请求懒加载 chunk 时失败。',
      '排查更新问题时看 Network 的响应头、状态码、文件名与 CDN 行为，区分浏览器缓存、CDN 缓存和服务端返回。',
    ],
    followUp: '部署后用户打开旧页面，再点击一个懒加载路由出现 chunk 404，如何处理？',
    refs: ['cache', 'webpackSplitting'],
  },
  {
    id: 'perf-list', category: 'performance', level: '进阶', title: '大列表该用分页、无限滚动还是虚拟列表？',
    brief: '分别解决数据获取、浏览方式和 DOM 数量的问题。',
    answer: [
      '分页把数据和导航分成明确的页，适合可定位、可回看或有筛选结果的列表。无限滚动按需加载数据，适合连续浏览，但需要处理加载状态、位置恢复和终点。',
      '虚拟列表只挂载可见区域附近的 DOM，解决一次渲染太多节点的问题；它不自动减少服务端数据量。数据很多时可把服务端分页或增量加载与客户端虚拟化结合。',
      '选型时还要考虑动态行高、可访问性、搜索定位、选中状态和滚动恢复。性能图应衡量实际用户场景，不只比较首次 DOM 数量。',
    ],
    followUp: '虚拟列表滚到中间后刷新页面，如何恢复位置且避免内容跳动？',
    refs: ['virtualization'],
  },
  {
    id: 'perf-monitor', category: 'performance', level: '实战', title: '线上性能优化如何形成“发现—定位—验证”的闭环？',
    brief: '真实用户数据、实验室复现和版本对比要连起来看。',
    answer: [
      '先定义业务关键页面和体验目标，采集 LCP、INP、CLS 等真实用户指标，并按设备、网络、地区和页面版本切分。只看全站平均值容易掩盖低端设备或某条关键链路的问题；通常还要关注第 75 百分位。',
      '发现异常后，结合浏览器 Performance、网络瀑布、服务端日志和版本变更复现瓶颈。为优化假设建立可量化指标，例如“首屏关键图发现时间降低”或“长任务数量减少”，一次优先改一个主要瓶颈。',
      '上线后对比同口径用户群与时间窗口，观察回归和副作用；必要时灰度或回滚。监控上报应控制采样与数据量，避免采集敏感信息或让监控脚本本身影响性能。',
    ],
    followUp: '为什么一次 Lighthouse 分数提升，不一定代表线上用户体验已经改善？',
    refs: ['vitals', 'inp'],
  },
  {
    id: 'perf-requests', category: 'performance', level: '实战', title: '页面同时发出大量请求，如何控制并发、缓存、取消与重试？',
    brief: '从请求必要性和依赖关系入手，再设计调度策略。',
    answer: [
      '先区分首屏必需、可延后和重复请求，合并相同资源或利用 HTTP 缓存。相互独立的请求可并行，但成百上千个任务不宜一次性 Promise.all；应限制并发量，避免占满连接、主线程和服务端容量。',
      '搜索联想等过期请求可用 AbortController 取消，或至少在回调中校验请求版本，防止旧结果覆盖新结果。失败重试应只针对合适的错误，设置次数上限与退避间隔；非幂等操作不能不加区分地自动重试。',
      '面试回答要给出观测指标：请求排队、成功率、超时率、缓存命中率与关键页面耗时。并发数不是越大越快，应在实际网络和服务端容量下测量。',
    ],
    followUp: '用户快速连续输入三个关键词，如何保证页面只展示最后一次查询结果？',
    refs: ['promises', 'abortController', 'cache'],
  },

  {
    id: 'webpack-loader-plugin', category: 'webpack', level: '基础', title: 'Loader 与 Plugin 的职责有什么区别？',
    brief: 'Loader 转换模块内容，Plugin 在构建生命周期里扩展行为。',
    answer: [
      'Loader 主要针对匹配的模块做内容转换，例如把一种源码形式处理成构建能继续理解的模块。多个 Loader 会形成处理链，配置顺序与执行顺序要分清。',
      'Plugin 通过 apply 方法注册到 Webpack 的生命周期钩子，可以参与更广的编译过程，例如生成资源、注入环境常量或分析产物。',
      '回答时给出具体边界：处理某类文件内容多用 Loader；需要跨模块、跨 chunk 或产物级操作时考虑 Plugin。',
    ],
    example: 'module.exports = {\n  module: { rules: [{ test: /\\.css$/, use: ["style-loader", "css-loader"] }] },\n  plugins: [new HtmlWebpackPlugin()]\n};',
    followUp: '为什么 css-loader 与 style-loader 的配置顺序看起来和执行顺序相反？',
    refs: ['webpackLoaders', 'webpackPlugins'],
  },
  {
    id: 'webpack-graph', category: 'webpack', level: '基础', title: 'Webpack 从 entry 到 output，中间为什么要构建模块依赖图？',
    brief: '从入口解析 import/require，形成模块与 chunk 的关系。',
    answer: [
      'Webpack 从配置的 entry 出发解析依赖，把每个模块及它依赖的模块纳入图中，并依据配置做转换和优化。最终会把模块组织进一个或多个 chunk，再输出浏览器可加载的资源。',
      '模块、chunk 和最终文件不是完全同义词：模块是源码依赖节点；chunk 是打包组织单位；一个输出文件可能对应一个或多个相关产物。',
      '理解依赖图有助于解释循环依赖、共享模块抽取、动态导入和为什么某个包进入首屏 bundle。',
    ],
    followUp: '静态 import 与动态 import 在依赖图和加载时机上有何差异？',
    refs: ['webpackConcepts', 'webpackSplitting'],
  },
  {
    id: 'webpack-split', category: 'webpack', level: '实战', title: '如何用动态 import 与 SplitChunks 缩小入口包？',
    brief: '动态导入建立异步边界，SplitChunks 抽取满足条件的共享代码。',
    answer: [
      'import() 可以把低频功能放到异步 chunk，在真正需要时加载；路由、弹窗编辑器和大型图表是常见候选。SplitChunks 则可按共享次数、大小和缓存组等条件提取公共依赖，避免多入口重复打包。',
      '切分不是越细越好。过多小请求、额外运行时开销和加载瀑布会抵消收益；需要分析构建产物、首屏请求链和缓存命中率。',
      '落地时为异步模块提供 loading/error 状态，并考虑部署期间旧页面请求新旧 chunk 的兼容问题。',
    ],
    example: 'const Editor = React.lazy(() => import("./Editor"));\n// 页面需要编辑器时再请求对应的异步 chunk',
    followUp: '共享依赖抽到单独 chunk 后，为什么有时更利于缓存，有时却会增加首屏请求？',
    refs: ['webpackSplitting'],
  },
  {
    id: 'webpack-tree', category: 'webpack', level: '进阶', title: 'Tree shaking 依赖什么？sideEffects: false 为什么可能把样式弄丢？',
    brief: 'ESM 的静态结构和副作用信息共同决定能否安全删除代码。',
    answer: [
      'Tree shaking 利用静态 import/export 分析哪些导出被使用，再在生产优化阶段移除未使用代码。动态行为和模块顶层副作用会限制可删除范围。',
      'package.json 的 sideEffects: false 是“这些文件没有导入即执行的副作用”提示。若组件导入了 CSS、polyfill 或全局注册逻辑，却错误地把它们都标为无副作用，构建器可能将这些文件整段移除。',
      '更稳妥的做法是把确有副作用的文件列在 sideEffects 白名单中，例如 CSS；然后检查生产产物和实际功能，不能只看构建是否成功。',
    ],
    example: '{ "sideEffects": ["**/*.css"] }\n// 样式文件保留副作用，其他可安全删除的模块可继续优化',
    followUp: '为什么把 CommonJS 包换成 ESM 版本，通常更利于静态分析？',
    refs: ['webpackTree'],
  },
  {
    id: 'webpack-cache', category: 'webpack', level: '实战', title: 'Webpack 构建越来越慢，应该先查什么？持久化缓存能做什么？',
    brief: '先定位耗时阶段，再决定缓存、缩小处理范围或调整并行度。',
    answer: [
      '先采集构建耗时和产物信息，确认瓶颈在模块解析、Loader 转换、压缩还是文件系统。盲目增加线程可能使小项目更慢，也可能掩盖过宽的 Loader 匹配规则。',
      'Webpack 5 的 filesystem cache 可把部分构建结果持久化到磁盘，加快后续构建；缓存是否有效与配置、依赖及文件变化有关。开发环境还应避免不必要的高成本 source map 与全量优化。',
      '长期方案包括缩小 Loader include 范围、检查重复依赖、调整拆包策略，并分别比较冷构建与热更新指标。',
    ],
    followUp: '为什么“第二次构建很快”不能证明冷启动体验也很好？',
    refs: ['webpackCache'],
  },
  {
    id: 'webpack-hmr', category: 'webpack', level: '进阶', title: 'HMR 与浏览器整页刷新有什么区别？什么时候会回退为刷新？',
    brief: 'HMR 尝试替换受影响模块并保留页面状态。',
    answer: [
      'HMR 在运行中的应用接收更新模块，尝试在合适边界接受并替换它，通常比整页刷新更快，也可能保留部分应用状态。整页刷新则重新加载文档和所有应用初始化逻辑。',
      '如果更新沿依赖链找不到可接受的 HMR 边界、模块处理方式不支持热替换，或更新的是必须重新初始化的配置，工具可能触发整页刷新。',
      'HMR 是开发期能力，不应依赖它保证业务状态正确。某些副作用如果没有正确清理，热更新后可能出现重复监听或旧实例残留。',
    ],
    followUp: '为什么改一个样式文件通常可热更新，而改某些入口配置会重启服务？',
    refs: ['webpackHmr'],
  },

  {
    id: 'vite-dev-build', category: 'vite', level: '基础', title: 'Vite 6 开发服务器为什么启动快？生产环境还需要打包吗？',
    brief: '开发期按需提供原生 ESM；生产期仍要优化请求与产物。',
    answer: [
      '在本项目的 Vite 6 中，开发服务器以浏览器原生 ESM 为基础，源码按请求转换与提供，不必先把整个应用打成一个开发包。依赖预打包由 esbuild 完成，帮助处理 CommonJS 兼容与大量小模块请求。',
      '生产构建仍需要打包、Tree shaking、压缩和合理拆包，以减少大量嵌套模块请求及提升缓存效率。Vite 6 的生产构建以 Rollup 为核心，不应把“Vite 用 esbuild”直接概括成生产打包也由 esbuild 完成。',
      'Vite 后续主版本的底层工具可能变化，讨论实现时应先说明版本；比较 Webpack 与 Vite 时也要区分开发体验和生产产物。',
    ],
    followUp: '为什么浏览器已经支持 ESM，生产环境仍可能选择打包？',
    refs: ['viteWhy', 'viteDeps'],
  },
  {
    id: 'vite-deps', category: 'vite', level: '进阶', title: 'Vite 6 为什么要预打包依赖？node_modules/.vite 缓存何时失效？',
    brief: '兼容 CommonJS，并把依赖中过多的小模块合并。',
    answer: [
      '开发时 Vite 用原生 ESM 提供源码，但一些依赖仍以 CommonJS/UMD 发布，或内部包含大量 ESM 文件。预打包可以转换不兼容格式并减少浏览器对依赖的请求数量。',
      '预打包结果缓存到 node_modules/.vite。锁文件、相关配置或依赖版本变化时会重新处理；遇到缓存异常可用 vite --force 触发重建。',
      '预打包是开发期依赖优化，不应与生产构建的拆包混为一谈。某个依赖无法被静态扫描到时，可再看 optimizeDeps.include 等配置。',
    ],
    followUp: '为什么源码模块不一定像第三方依赖一样预打包？',
    refs: ['viteDeps'],
  },
  {
    id: 'vite-hmr', category: 'vite', level: '进阶', title: 'Vite 的 HMR 为什么通常较快？React Fast Refresh 又负责什么？',
    brief: '模块图精准失效；React 集成负责组件更新与状态保留边界。',
    answer: [
      'Vite 开发期沿模块依赖图找到受影响模块及最近的 HMR 边界，仅让浏览器获取需要更新的模块，而不是重建整个开发 bundle。更新范围越局部，反馈通常越快。',
      'React 项目中的 Fast Refresh 由 React 集成提供，尝试在组件更新时保留兼容的本地状态。若组件签名变化或模块不再是安全边界，可能重置状态甚至回退到刷新。',
      '调试“改文件后整页刷新”时，要看模块的导出、插件处理和 HMR 边界，不应只归因于 Vite 启动速度。',
    ],
    followUp: '为什么修改一个组件的 Hook 顺序可能使本地状态无法保留？',
    refs: ['viteWhy', 'viteFeatures'],
  },
  {
    id: 'vite-env', category: 'vite', level: '基础', title: 'import.meta.env.MODE、DEV 与 VITE_ 变量分别是什么？能存密钥吗？',
    brief: '模式名与开发状态不是同一维度；暴露到客户端的变量不保密。',
    answer: [
      'MODE 是当前模式名称；DEV/PROD 是布尔环境标识。自定义 .env.[mode] 文件可按模式加载配置，读取时注意变量值通常是字符串，需要自行做类型转换。',
      '默认只有 VITE_ 前缀的自定义变量会暴露给客户端代码，构建时可能进入最终资源，任何访问页面的人都可能查看。API 私钥、数据库密码等必须留在服务端。',
      '修改 .env 后通常需要重启开发服务器。排查配置错误要同时确认模式、文件优先级、前缀和代码读取位置。',
    ],
    example: 'const apiBase = import.meta.env.VITE_API_BASE;\nconst isDev = import.meta.env.DEV;\n// VITE_API_BASE 是公开配置，不应存放密钥',
    followUp: '为什么 .env.production 中的 VITE_TOKEN 仍不能当秘密？',
    refs: ['viteEnv'],
  },
  {
    id: 'vite-dynamic', category: 'vite', level: '实战', title: 'Vite 中 import() 的开发行为与生产拆包有什么不同？',
    brief: '开发期按需请求模块；生产期形成异步加载边界。',
    answer: [
      '开发时 import() 在执行到该分支时请求对应模块，便于快速反馈；生产构建会把动态导入作为异步边界，输出相应 chunk，并在需要时加载。',
      '适合路由级页面、低频编辑器或图表等较大的功能；同时要给用户可见的 loading 与失败处理。把首屏立刻需要的代码都改成动态导入，可能制造额外请求瀑布。',
      '评估时看构建产物、首屏网络瀑布和真实交互延迟，不要仅以入口文件变小为成功标准。',
    ],
    example: 'async function openEditor() {\n  const { createEditor } = await import("./editor.js");\n  return createEditor();\n}',
    followUp: '如何处理部署后旧页面请求已被清理的异步 chunk？',
    refs: ['viteBuild', 'viteFeatures'],
  },
  {
    id: 'vite-migrate', category: 'vite', level: '实战', title: '从 Webpack 迁移到 Vite，为什么不能只替换启动命令？',
    brief: '要检查环境变量、模块写法、插件、资源路径和开发构建差异。',
    answer: [
      '先清点 Webpack Loader/Plugin 的用途：它们可能在做源码转换、全局变量注入、资源路径处理或构建后操作。Vite 使用不同的插件接口和资源约定，通常需要选择对应插件或改写配置，而非直接复制 Webpack 配置。',
      '检查 process.env 迁移到 import.meta.env、CommonJS 依赖兼容、路径别名、public 目录、动态导入、CSS 处理和代理配置。然后分别验证开发服务器与生产构建，避免“开发能跑，打包失败”。',
      '用关键页面、测试和产物分析做迁移验收；不要仅凭启动时间判断迁移收益，还应比较 HMR、构建速度与线上加载表现。',
    ],
    followUp: 'Webpack 中通过 DefinePlugin 注入的变量，迁到 Vite 后应如何区分公开配置与服务端秘密？',
    refs: ['vitePlugins', 'viteEnv', 'viteBuild'],
  },
]

const allArchiveQuestions = [...baseArchiveQuestions, ...extraQuestions]
export const archiveQuestions = archiveCategories.flatMap(category =>
  allArchiveQuestions.filter(question => question.category === category.id),
)
